--CLAUSES GROUP BY

SELECT * FROM Employees

SELECT DESIGNATION, COUNT(*) NUMBEROFEMPLOYEE FROM Employees GROUP BY Designation

SELECT Designation, SUM(SALARY),AVG(SALARY),MAX(Salary),MIN(Salary) FROM Employees GROUP BY Designation

SELECT DESIGNATION, COUNT(*) NUMBEROFEMPLOYEE FROM Employees GROUP BY Designation

---HAVING CLAUSE
SELECT DESIGNATION, COUNT(*) NUMBEROFEMPLOYEE FROM Employees GROUP BY Designation HAVING COUNT(*)<3

SELECT DESIGNATION, SUM(SALARY) NUMBEROFEMPLOYEE FROM Employees GROUP BY Designation HAVING SUM(SALARY)<34000
