--CURSOR

SELECT * FROM EMP

INSERT INTO EMP VALUES(105,'SIMRAN','TESTER'),(106,'SAGUNA','DEVELOPER'),(107,'SAPNA','SALES'),(108,'RAGHAV','HR'),(109,'SIDHHARTH','tester'),(110,'SUMIT','HR')

--WITHOUT CURSOR VARIABLES
DECLARE C1 CURSOR SCROLL FOR SELECT * FROM EMP
OPEN C1
FETCH FIRST FROM C1
FETCH LAST FROM C1
FETCH PRIOR FROM C1
FETCH NEXT FROM C1
FETCH ABSOLUTE 7 FROM C1
FETCH RELATIVE 3 FROM C1
CLOSE C1
DEALLOCATE C1

--WITH CURSOR VARIABLES
DECLARE C1 CURSOR SCROLL FOR SELECT EID,ENAME FROM EMP
DECLARE @EID INT, @ENAME VARCHAR(100) 
OPEN C1
FETCH LAST FROM C1 INTO @EID, @ENAME
PRINT'THE EMPLOYEE NAME '+@ENAME+' '+'ID IS :- '+CAST(@EID AS VARCHAR)

FETCH FIRST FROM C1 INTO @EID, @ENAME
PRINT'THE EMPLOYEE NAME '+@ENAME+' '+'ID IS :- '+CAST(@EID AS VARCHAR)

FETCH NEXT FROM C1 INTO @EID, @ENAME
PRINT'THE EMPLOYEE NAME '+@ENAME+' '+'ID IS :- '+CAST(@EID AS VARCHAR)

FETCH PRIOR FROM C1 INTO @EID, @ENAME
PRINT'THE EMPLOYEE NAME '+@ENAME+' '+'ID IS :- '+CAST(@EID AS VARCHAR)

FETCH ABSOLUTE 5 FROM C1 INTO @EID, @ENAME
PRINT'THE EMPLOYEE NAME '+@ENAME+' '+'ID IS :- '+CAST(@EID AS VARCHAR)

FETCH RELATIVE 2 FROM C1 INTO @EID, @ENAME
PRINT'THE EMPLOYEE NAME '+@ENAME+' '+'ID IS :- '+CAST(@EID AS VARCHAR)

CLOSE C1
DEALLOCATE C1
