---CURSOR

SELECT * FROM EMPLOYEE

--DECLARE VARIABLES
DECLARE @EMP_ID INT,
@FIRSTNAME VARCHAR(100),
@DESIGNATION VARCHAR(100),
@CITY VARCHAR(100),
@DOB DATE,
@SALARY INT 

DECLARE @TOTALSAL INT

--DECLARE CURSOR
DECLARE CURSOR_EMP CURSOR FOR SELECT EMP_ID,FIRSTNAME,DESIGNATION,CITY,DOB,SALARY FROM EMPLOYEE

--OPEN CURSOR
OPEN CURSOR_EMP

FETCH NEXT FROM CURSOR_EMP INTO @EMP_ID,@FIRSTNAME,@DESIGNATION,@CITY,@DOB,@SALARY

WHILE @@FETCH_STATUS=0
PRINT CONCAT('EMP_ID:-' , '@EMP_ID');
PRINT CONCAT('FIRSTNAME:-' , '@FIRSTNAME');
PRINT CONCAT('DESIGNATION:-' , '@DESIGNATION');
PRINT CONCAT('CITY:-' , '@CITY');
PRINT CONCAT('DOB:-' , '@DOB');
PRINT CONCAT('SALARY:-' , '@SALARY');

SET @TOTALSAL=@SALARY*10;

PRINT CONCAT('TOTALSAL:-', '@TOTALSAL')