--IDENTITY
CREATE TABLE Orders(OID INT IDENTITY primary key,ONAME VARCHAR(100))

SELECT * FROM Orders

INSERT INTO Orders VALUES('SAGUNA'),('RANI')

CREATE TABLE Orders2(OID INT IDENTITY(100,5) primary key,ONAME VARCHAR(100))

SELECT * FROM Orders2

INSERT INTO Orders2 VALUES('SAGUNA'),('RANI')

SET IDENTITY_INSERT ORDERS ON INSERT INTO Orders2(ONAME)VALUES ('KRISHMA')

SET IDENTITY_INSERT ORDERS OFF INSERT INTO Orders2(ONAME)VALUES ('GARGI')