--SP INPUT PARAMETER

SELECT * FROM EMPLOYEE

CREATE PROCEDURE SP_INPUT(
@EMP_ID INT,
@FIRSTNAME VARCHAR(100),
@DESIGNATION VARCHAR(100),
@CITY VARCHAR(100),
@DOB DATE,
@SALARY INT)
AS
BEGIN
INSERT INTO EMPLOYEE VALUES(@FIRSTNAME,@DESIGNATION,@CITY,@DOB,@SALARY)
END

EXECUTE SP_INPUT 'GANESH','DOTNET DEVELOPER' , 'KARNATKA' , '01/03/2098', 78000;