--CREATE LEAVE MANAGEMENT SYSTEM DATABASE

CREATE DATABASE LEAVE_MANAGEMENT_SYSTEM

---CREATE TABLE EMPLOYEE
CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY IDENTITY NOT NULL,
FIRSTNAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL,
AGE INT NOT NULL,
CITY VARCHAR(100),
GENDER VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
MOBILENUM BIGINT NOT NULL,
DEPT_ID INT NOT NULL,
DEPT_NAME VARCHAR(100) NOT NULL)

SELECT * FROM EMPLOYEE

--INSERT RECORDS INTO EMPLOYEE TABLE
INSERT INTO EMPLOYEE VALUES('SAGUNA','UKADE',24,'PUNE','FEMALE','SAGUNAUKADE12@GMAIL.COM',8974856543,1,'SOFTWARE DEVELOPER');
INSERT INTO EMPLOYEE VALUES('RANI','JADHAV',34,'NASHIK','FEMALE','RANI987@GMAIL.COM',3265417895,2,'JAVA DEVELOPER');
INSERT INTO EMPLOYEE VALUES('KRISHMA','SHRMA',25,'CHENNAI','FEMALE','KRISHMA234@GMAIL.COM',8899554152,3,'HR');
INSERT INTO EMPLOYEE VALUES('RAGHAV','VARMA',31,'BANGLORE','MALE','RAGHAV654@GMAIL.COM',7845123698,4,'MANAGER');
INSERT INTO EMPLOYEE VALUES('PRNALI','KULKARNI',28,'KOLHAPUR','FEMALE','PRNALI45@GMAIL.COM',5987463214,5,'TESTING');
INSERT INTO EMPLOYEE VALUES('KARTIK','SHINDE',22,'DELHI','MALE','KARTIK123@GMAIL.COM',78956412356,6,'SQL DEVELOPER');

---CREATE TABLE DEPARTMENT
CREATE TABLE DEPARTMENT(
DEPT_ID INT NOT NULL PRIMARY KEY,
DEPT_NAME VARCHAR(100))

SELECT * FROM DEPARTMENT

--INSERT RECORDS INTO DEPARTMENT TABLE
INSERT INTO DEPARTMENT VALUES(1,'JAVA DEVELOPER');
INSERT INTO DEPARTMENT VALUES(2,'HR');
INSERT INTO DEPARTMENT VALUES(3,'SQL DEVELOPER');
INSERT INTO DEPARTMENT VALUES(4,'MANAGER');
INSERT INTO DEPARTMENT VALUES(5,'MARKETING');

---CREATE TABLE LEAVE TYPE
CREATE TABLE LEAVE_TYPE(
DEPT_ID INT,
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),
EMP_ID INT,
LEAVE_NAME VARCHAR(200),
NUM_OF_DAYS INT NOT NULL)

SELECT * FROM LEAVE_TYPE

--INSERT RECORDS INTO LEAVE TYPE TABLE
INSERT INTO LEAVE_TYPE VALUES(1,1,'SICK LEAVE',1);
INSERT INTO LEAVE_TYPE VALUES(2,2,'CASUAL LEAVE',3);
INSERT INTO LEAVE_TYPE VALUES(3,3,'MARRIAGE LEAVE',4);
INSERT INTO LEAVE_TYPE VALUES(4,4,'EARNED LEAVE',2);
INSERT INTO LEAVE_TYPE VALUES(5,5,'CASUAL LEAVE',1);

---CREATE TABLE LEAVE APPPLICATION 
CREATE TABLE LEAVE_APPPLICATION(
EMP_ID INT NOT NULL,
DATE_OF_APPLICATION DATE,
LEAVE_NAME VARCHAR(100),
LEAVE_DESCRIPTION VARCHAR(500),
FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID))

SELECT * FROM LEAVE_APPPLICATION

--INSERT RECORDS INTO LEAVE APPPLICATION TABLE
INSERT INTO LEAVE_APPPLICATION VALUES(1,'01/09/2022','SICK LEAVE','I AM DOWN WITH FEVER AND FLU BCZ OF WHICH I WILL NOT BE ABLE TO COME TO OFFICE FOR ATLEAT 1DAY');
INSERT INTO LEAVE_APPPLICATION VALUES(2,'09/05/22','CASUAL LEAVE','I HAVE IMPORTANT PERSONAL ISSUES TO ATTEND AT MY HOMETOWN');
