create table customers(CID INT PRIMARY KEY IDENTITY,
FIRSTNAME VARCHAR(100),
LASTNAME VARCHAR(100),
CITY VARCHAR(100),
MOBILENUM BIGINT,
DOB DATE,
AGE INT
)

insert into customers values('SAGUNA','UKADE','PUNE',4587965478,'01/03/2022',23)
insert into customers values('BHARTI','KADAM','CHENNAI',9876543212,'11 FEB 2012',23)
insert into customers values('GANESH','VARMA','NSK',7654321234,'12 JUN 2022',12)
insert into customers values('KAJAL','JADHAV','PUNE',8954671236,'25 JUN 2020',21)
insert into customers values('RUPALI','PARAS','DELHI',4589658712,'3 MARCH 2018',27)

SELECT * FROM CUSTOMERS

CREATE TABLE ORDERS1(OID INT ,
NAME VARCHAR(100),
ADDRESS VARCHAR(100),
CID INT FOREIGN KEY REFERENCES CUSTOMERS(CID))

SELECT * FROM ORDERS1

INSERT INTO ORDERS1 VALUES(1,'ARNAV','DUBAI',1),(2,'CHETAN','MP',2)

SELECT * FROM Employees

--ROLLUP
SELECT DESIGNATION, COUNT(*) FROM EMPLOYEES GROUP BY ROLLUP(Designation)

--CUBE
SELECT DESIGNATION, COUNT(*) FROM EMPLOYEES GROUP BY ROLLUP(Designation)

--ROLLUP
SELECT DESIGNATION, COUNT(*),Emp_Id FROM EMPLOYEES GROUP BY ROLLUP(Designation,EMP_ID)

--CUBE
SELECT DESIGNATION, COUNT(*),Emp_Id FROM EMPLOYEES GROUP BY CUBE(Designation,EMP_ID)


SELECT * FROM EMP1

SELECT * FROM EMPLOYEES

SELECT DESIGNATION, COUNT(SALARY) FROM EmployeeS GROUP BY DESIGNATION