select * from employees

create proc SP_GETALLEMPLOYEES
AS
BEGIN
SELECT * FROM Employees
END

EXEC SP_GETALLEMPLOYEES

ALTER PROC SP_INSERTEMP
AS
BEGIN
INSERT INTO Employees(FIRSTNAME,DESIGNATION,CITY,DOB,SALARY) VALUES('SAGUNA','SOFTWARE DEVELOPER','PUNE','12 JUNE 1996',40000)
END

EXEC SP_INSERTEMP

CREATE PROCEDURE SP_GETEMPLOYEE
AS
BEGIN
SELECT FIRSTNAME,DESIGNATION,CITY,SALARY FROM EMPLOYEES 
ORDER BY FIRSTNAME
END

EXEC SP_GETEMPLOYEE

CREATE PROC SP_UPDATEEMP
AS
BEGIN
UPDATE EMPLOYEES SET DESIGNATION='MANAGER' WHERE EMP_ID=9
END

EXEC SP_UPDATEEMP

SELECT * FROM Employees

CREATE PROC SP_DELETEEMP
AS
BEGIN
DELETE FROM EMPLOYEES WHERE EMP_ID=8
END

EXEC SP_DELETEEMP

ALTER PROC SP_EMPLOYEES
@EMP_ID INT
AS
BEGIN
SELECT * FROM EMPLOYEES WHERE EMP_ID=@EMP_ID
END

EXEC SP_EMPLOYEES 5

CREATE PROC SP_EMPLOYEES1
@CITY VARCHAR(100)
AS
BEGIN
SELECT * FROM EMPLOYEES WHERE CITY=@CITY
END

EXEC SP_EMPLOYEES1 'PUNE'

ALTER PROC SP_UPDATEEMP1
@FIRSTNAME VARCHAR(100),
@CITY VARCHAR(100)
AS
BEGIN
UPDATE EMPLOYEES SET Firstname=@FIRSTNAME,City=@CITY
WHERE EMP_ID=3
END

EXEC SP_UPDATEEMP1  @FIRSTNAME='LAVANYA',@CITY='GUJRAT'

EXEC SP_RENAME 'EMPLOYEES','EMPLOYEE'

SELECT * FROM Employee

DECLARE @SALARY INT
SET @SALARY=230000
SELECT FIRSTNAME,CITY,SALARY FROM EMPLOYEE
WHERE SALARY=@SALARY
ORDER BY FIRSTNAME


