---STORED PROCEDURE WITH OUT PARAMETER

SELECT * FROM Employees

CREATE PROCEDURE SP_EMP2(@EMP_ID INT,@PF INT OUT, @PT INT OUT)
AS
BEGIN
DECLARE @SAL INT
SELECT @SAL=SALARY FROM Employees WHERE EMP_ID=@EMP_ID
SET @PF=@SAL*0.1
SET @PT=@SAL*0.2
END

---OUTPUT
DECLARE @bPF INT
DECLARE @bPT INT
EXEC SP_EMP2 2,@bPF OUT,@bPT OUT
PRINT 'PROVIDENT FUND IS:-' + CAST( @bPF AS VARCHAR)
PRINT 'PROFESSIONAL TAX IS:-' + CAST( @bPT AS VARCHAR)

--INPUT PARAMETER

SELECT * FROM Employees

CREATE PROC SP_EMP_IN(
@EMP_ID INT,
@FIRSTNAME VARCHAR(100),
@DESIGNATION VARCHAR(100),
@CITY VARCHAR(100),
@DOB DATE,
@SALARY INT)
AS
BEGIN
INSERT INTO Employees VALUES(@FIRSTNAME,@DESIGNATION ,@CITY, @DOB,@SALARY)
END

EXEC SP_EMP_IN @EMP_ID='EMP_ID', @FIRSTNAME='FIRSTNAME',@DESIGNATION='DESIGNATION',@CITY='CITY',@DOB='DOB',@SALARY='SALARY';

SELECT FIRSTNAME FROM EMPLOYEES

SELECT UPPER(FIRSTNAME) AS FIRSTNAME FROM Employees

SELECT LOWER(FIRSTNAME) AS FIRSTNAME FROM EMPLOYEES

SELECT FIRSTNAME FROM EMPLOYEES WHERE FIRSTNAME='PALLAVI'

SELECT * FROM EMPLOYEES WHERE FIRSTNAME LIKE '%A'

SELECT * FROM EMPLOYEES WHERE FIRSTNAME LIKE 'P%'

SELECT * FROM EMPLOYEES WHERE Firstname LIKE '%S%'

SELECT GETDATE()

SELECT GETUTCDATE()

SELECT FIRSTNAME, CITY ,DOB FROM EMPLOYEES 

SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 23000 AND 50000

SELECT TOP 1 * FROM Employees

SELECT TOP 5 * FROM EMPLOYEES

SELECT * FROM Employees WHERE FIRSTNAME IN('KRISMA','PRACHI','AMRUTA')

SELECT * FROM EMPLOYEES WHERE FIRSTNAME NOT IN('PRACHI','AMRUTA')

SELECT RTRIM(FIRSTNAME) AS [FIRSTNAME] FROM EMPLOYEES

SELECT 'HELLO' +' '+ FIRSTNAME FROM EMPLOYEES

SELECT 'HELLO EVERYONE' + ' ' + FIRSTNAME FROM EMPLOYEES

CREATE PROCEDURE FACTNUM
( @Number Integer,@RetVal Integer OUTPUT )

AS
    DECLARE @In Integer
    DECLARE @Out Integer
    IF @Number != 1
        BEGIN
        SELECT @In = @Number-1
        EXEC FACTNUM @In, @Out OUTPUT
        SELECT @RetVal = @Number * @Out
    END
        ELSE
            BEGIN
                SELECT @RetVal = 1
            END
RETURN
GO
