--SUBQUERIES
SELECT * FROM Employees

SELECT MAX(SALARY) FROM EMPLOYEES

SELECT * FROM Employees WHERE SALARY=(SELECT MAX(SALARY) FROM Employees)

SELECT * FROM EMPLOYEES WHERE Designation IN(SELECT Designation FROM Employees WHERE FIRSTNAME='PALLAVI' AND Firstname='PRACHI')

SELECT * FROM EMPLOYEES WHERE DESIGNATION IN(SELECT Designation FROM Employees WHERE FIRSTNAME IN('RANI','PRACHI'))