--TCL
--TO PERFORM SOME OPERATION
---INSERT,UPDATE,DELETE

SELECT * FROM BRANCH

CREATE TABLE BRANCH(BCODE INT,
BNAME VARCHAR(100),LOCATION VARCHAR(100))

INSERT INTO BRANCH VALUES(101,'BOB','NSK'),(102,'SBI','PUNE')

UPDATE BRANCH SET LOCATION='DELHI' WHERE BCODE=101

DELETE FROM BRANCH WHERE BCODE=102

BEGIN TRANSACTION
ROLLBACK

select * from branch

---example-1
BEGIN TRANSACTION
INSERT INTO BRANCH VALUES(103,'BOI','DELHI');
COMMIT

BEGIN TRANSACTION 
ROLLBACK

--EXAMPLE-2
BEGIN TRANSACTION
UPDATE BRANCH SET LOCATION='NSK' WHERE BCODE=102
COMMIT

BEGIN TRANSACTION 
ROLLBACK

--EXAMPLE-3
BEGIN TRANSACTION
DELETE FROM BRANCH WHERE BCODE=102
COMMIT

BEGIN TRANSACTION
ROLLBACK

--SAVEPOINT
BEGIN TRANSACTION
DELETE FROM BRANCH WHERE BCODE=103
DELETE FROM BRANCH WHERE BCODE=101
SAVE TRANSACTION S1
DELETE FROM BRANCH WHERE BCODE=104

BEGIN TRANSACTION
ROLLBACK

--SAVEPOINT 
BEGIN TRANSACTION
DELETE FROM BRANCH WHERE BCODE=103
DELETE FROM BRANCH WHERE BCODE=101
COMMIT
SAVE TRANSACTION S1
DELETE FROM BRANCH WHERE BCODE=104

BEGIN TRANSACTION
ROLLBACK

SELECT * FROM BRANCH